const motivationalQuotes: string[] = [
  `The only way to do great work is to love what you do. - Steve Jobs`,
  `Believe you can and you're halfway there. - Theodore Roosevelt`,
  `Your limitation - it's only your imagination.`,
  `Push yourself, because no one else is going to do it for you.`,
  `Great things never come from comfort zones.`,
  `Dream it. Wish it. Do it.`,
  `Success doesn't just find you. You have to go out and get it.`,
  `The harder you work for something, the greater you'll feel when you achieve it.`,
  `Dream bigger. Do bigger.`,
  `Don't stop when you're tired. Stop when you're done.`,
  `Wake up with determination. Go to bed with satisfaction.`,
  `Do something today that your future self will thank you for.`,
  `Little things make big days.`,
  `It's going to be hard, but hard does not mean impossible.`,
  `Don't wait for opportunity. Create it.`,
  `Sometimes we're tested not to show our weaknesses, but to discover our strengths.`,
  `The key to success is to focus on goals, not obstacles.`,
  `Dream it. Believe it. Build it.`,
  `You don't have to be great to start, but you have to start to be great.`,
  `The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt`,
  `Believe in yourself and all that you are.`,
  `Work hard in silence, let your success be your noise.`,
  `Success is not how high you have climbed, but how you make a positive difference to the world.`,
  `The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt`,
  `Do what you can with all you have, wherever you are. - Theodore Roosevelt`,
  `You are never too old to set another goal or to dream a new dream. - C.S. Lewis`,
  `It always seems impossible until it's done. - Nelson Mandela`,
  `Your only limit is you.`,
  `Success is not the key to happiness. Happiness is the key to success. - Albert Schweitzer`,
  `The best time to plant a tree was 20 years ago. The second best time is now.`,
  `What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson`,
  `Keep your face always toward the sunshine—and shadows will fall behind you. - Walt Whitman`,
  `Don't watch the clock; do what it does. Keep going. - Sam Levenson`,
];

export default motivationalQuotes;
